<?php
/** @package Htools::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("AcessoMap.php");

/**
 * AcessoDAO provides object-oriented access to the perfil_acesso table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Htools::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class AcessoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $PerfilAcesso;

	/** @var string */
	public $TempoSessao;

	/** @var string */
	public $VelocidadeDownload;

	/** @var string */
	public $VelocidadeUpload;

	/** @var string */
	public $TrafegoMax;

	/** @var mediumtext */
	public $Descricao;


	/**
	 * Returns a dataset of Concentrador objects with matching CodPerfil
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCodPerfilConcentradors($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_perfil", $criteria);
	}

	/**
	 * Returns a dataset of PerfilSms objects with matching CodAcesso
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCodAcessoPerfilSmss($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_sms", $criteria);
	}


}
?>