<?php
/** @package Htools::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("EmpresaMap.php");

/**
 * EmpresaDAO provides object-oriented access to the empresa table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Htools::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class EmpresaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $NomeFantasia;

	/** @var string */
	public $RazaoSocial;

	/** @var string */
	public $Cnpj;

	/** @var string */
	public $Endereco;

	/** @var string */
	public $Site;

	/** @var string */
	public $Telefone;

	/** @var string */
	public $Telefone2;



}
?>