<?php
/** @package Htools::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("PerfilSmsMap.php");

/**
 * PerfilSmsDAO provides object-oriented access to the perfil_sms table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Htools::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class PerfilSmsDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Perfil;

	/** @var string */
	public $Mensagem;

	/** @var string */
	public $LinkUrl;

	/** @var int */
	public $CodAcesso;


	/**
	 * Returns the foreign object based on the value of CodAcesso
	 * @return PerfilAcesso
	 */
	public function GetCodAcessoPerfilAcesso()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_sms");
	}


}
?>